name: build

on:
  push:
    branches: [ main ]
    paths:
      - '**.cs'
      - '**.csproj'
      - '**.razor'

env:
  DOTNET_VERSION: '7.0.401'

jobs:
  build:
    name: build-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-22.04 ]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore